apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarqube
  namespace: sonarqube
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: sonarqube
    meta.helm.sh/release-namespace: sonarqube
spec:
  volumeName: sonarqube-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-sonarqube-postgresql-0
  namespace: sonarqube
spec:
  volumeName: postgresql-pv
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  resources:
    requests:
      storage: 3Gi

