apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: sonarqube

resources:
  - 01-namespace.yaml
  - 02-postgres-pv.yaml
  - 03-postgres-statefulset.yaml
  - 04-postgres-service.yaml
  - 05-sonarqube-pv-pvc.yaml
  - 06-sonarqube-deployment.yaml
  - 07-sonarqube-service.yaml
  - 08-sonarqube-ingress.yaml

